"""add payment fields to orders

Revision ID: 279c0497ad9c
Revises: 4118e577bdcf
Create Date: 2026-06-22 17:25:08.860797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279c0497ad9c'
down_revision: Union[str, Sequence[str], None] = '4118e577bdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('payment_status')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
