"""add pending_payments; remove PENDING_PAYMENT

Revision ID: 72182c1916a7
Revises: 96f269a27470
Create Date: 2026-06-23 01:24:44.577237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72182c1916a7'
down_revision: Union[str, Sequence[str], None] = '96f269a27470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_payments_razorpay_order_id'), ['razorpay_order_id'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('PAID', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PAID', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_payments_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_pending_payments_id'))

    op.drop_table('pending_payments')
    # ### end Alembic commands ###
