"""add is_featured to products

Revision ID: 96f269a27470
Revises: 8b68f3c7817e
Create Date: 2026-06-22 23:16:03.274871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f269a27470'
down_revision: Union[str, Sequence[str], None] = '8b68f3c7817e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=True))
        batch_op.create_index(batch_op.f('ix_products_is_featured'), ['is_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_featured'))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
