"""add_total_column_to_orders

Revision ID: faa0d6559131
Revises: 48b85ffeceb1
Create Date: 2026-06-22 13:00:39.630445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa0d6559131'
down_revision: Union[str, Sequence[str], None] = '48b85ffeceb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=True))
    op.execute("UPDATE orders SET total = 0.0 WHERE total IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###
